apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-test
  annotations:
    tekton.dev/title: "Go Unit Test Task"
spec:
  params:
    - description: The trusted artifact URI containing the application source code.
      name: SOURCE_ARTIFACT
      type: string
    - description: The Trusted Artifact URI pointing to the artifact with the prefetched dependencies.
      name: CACHI2_ARTIFACT
      type: string
      default: ""
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      # This path is hard coded in the cachi2.env file.
      - mountPath: /cachi2
        name: cachi2
    securityContext:
      # This is needed because the different steps in this Task run with different user IDs.
      runAsUser: 0
  steps:
    - image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:0e897921ea083450e8db518888159fd926ff10427c00009038726b4b1003c253
      name: use-trusted-artifact
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
        - $(params.CACHI2_ARTIFACT)=/cachi2
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:34492a70838d50a40f72adb126eeaae41d2cb6e054af829d16121da4dc7048e1
      workingDir: /var/workdir/source
      script: |
        #!/usr/bin/env sh
        if [ -f "/cachi2/cachi2.env" ]; then
          source "/cachi2/cachi2.env"
        fi
        CGO_ENABLED=0 go build -trimpath -o bin/timestamp-cli ./cmd/timestamp-cli
        CGO_ENABLED=0 go build -trimpath -o bin/timestamp-server ./cmd/timestamp-server
        go test ./...
  volumes:
    - name: workdir
      emptyDir: {}
    - name: cachi2
      emptyDir: {}
