apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-test
  annotations:
    tekton.dev/title: "Go Unit Test Task"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:75b74b4d4f589965d1d1d2086b951f543cf0c8152693a8640ea09a0c3b14f9e3
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/usr/bin/env sh
        CGO_ENABLED=0 go build -buildvcs=false -trimpath -o bin/timestamp-cli ./cmd/timestamp-cli
        CGO_ENABLED=0 go build -buildvcs=false -trimpath -o bin/timestamp-server ./cmd/timestamp-server
        go test ./...
        
# This file bundles the unit tests for the timestamp-authority. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/tsa-unit-test:latest -f .tekton/tsa-unit-test.yaml'.